name: CheckIfFilesAreGenerated

on:
  workflow_dispatch:
  schedule:
    - cron: "50 9 * * *"
jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check files
        env:
          IM_API_URL: ${{ secrets.IM_API_URL }}
        run: |
          TODAY=`date +"%Y-%m-%d"`
          FILE=./outputs/${TODAY}-*.csv

          if ls $FILE 1> /dev/null 2>&1; then
              echo "$FILE exists."
          else 
              echo "$FILE does not exist."

              curl $IM_API_URL \
                -H 'Content-Type: application/json' \
                -d '
                {
                     "msgtype": "text",
                     "text": {
                         "content": "whales buying altcoins - files not generated"
                     }
                }'
          fi
